apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semver-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/g33ta/sourcecode:~1.0
    #argocd-image-updater.argoproj.io/argocd.kustomize.image-name: nginx
spec:
  project: default

  source:
    repoURL: https://github.com/g33ta/argocd-applications.git
    targetRevision: HEAD
    path: ./applications/my-app
   
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
   
